### ISSUE TITLE
Code Review Request - Ed Ivimey-Cook

### ISSUE THREAD

**Issue by EIvimeyCook** [SORTEE/peer-code-review-resources#4]
**Author:** Ed Ivimey-Cook
**Repo:** https://github.com/EIvimeyCook/Peer_Code
**Aim:** Get feedback on proper code structure/syntax/layout.
**File Info:**  The main file is _Mutation Load.R_ which contains analysis and graphing functions relating to a recent project I was involved with. The other files _MeForest.R_, _Distribeaut.R_ are graphing functions using ggplot2 and _ModelChecker.R_ is a function to check poisson models for overdispersion.

**Comment by smwindecker** [comment]
Code Review: 27 July 2021
Present: @EIvimeyCook , @DrMattG, @wykhuh, @ecoisilva, @smwindecker 

Guiding your reader: 
- How do we navigate through your files?
- Some directory organisation would be good, eg. subfolders!
- a folder with functions? that a main file calls? Eg. `source(“myscript.R”)` or `R.utils::sourceDirectory(‘R/’)`
- or a range of scripts that go sequentially? > this could be aided with file numbering? could start with "01_..."
- instructions in the README to document these decisions!

Packages:
- Only load the ones you’re going to use! The libraries cost space

File paths:
- An R proj object so file paths are relative to project.
- [here](https://github.com/jennybc/here_here) package! Similar to setting working directory without having to change anything. Helps you work better in projects. And avoid the issue of different OS having different file path structure. 

Random stuff printed to console:
- Eg. `summary(object)` that you want in your supmat
- Can save as rdata object 
- `printed_a <- print(a); save(printed_a, file = 'test.Rdata')`
- If this is something that others will want to be able to reproduce or if it takes a while to run, this is a good idea to save.

Naming arguments
- Do we need to add the argument names inside functions? Eg. `ggplot(data = Data, … )`
- This would be helpful for readability!

How to make massive sections of code easier to look at?
- Consider, what are you repeating? Make those into a function and the item that changes is added as an argument. 
- A loop or a function will serve in this case! 
- [Loops](https://www.r-bloggers.com/2015/12/how-to-write-the-first-for-loop-in-r/). They’re fine! But can be slower than functions. If it’s a smaller bit of code, can be easy and readable. 

Tables for manuscripts
- Gah this is hard.
- gt ? 

Output
- How does the code relate to the published outputs?
- Uniqueness of output names
- And uniqueness of object names to avoid overwriting 

Cleaning up your main script: 
- Hide away your exploratory code
- Partition parts of your code into other scripts

Other
- What about clearing your env at the top of script? We’ll let Jenny take this one, see [here](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/), and [here](https://community.rstudio.com/t/project-oriented-workflow-setwd-rm-list-ls-and-computer-fires/3549)  
- [Speeding R code](http://www.dartistics.com/fast-r-code.html)
- Screen width! Keep it nice to read and narrow

Nice work! Thanks for sharing!
